/**
 * Ironclad Digital — runtime configuration.
 *
 * Centralize anything environment-specific here so the rest of the
 * codebase doesn't have to change when endpoints, keys, or feature
 * flags evolve. When a real backend ships, only this file (and any
 * deployment-specific override) needs to be updated.
 *
 * In production this can be replaced/overridden at deploy time
 * (e.g. via a templated config.js generated by the host).
 */
window.IRONCLAD_CONFIG = Object.freeze({
  // ---------- API ----------
  // Base URL of the backend API.
  // Local dev: 'http://localhost:3001'
  // Production: 'https://api.ironcladdigital.agency'
  // Leave empty to run in mock mode (no server needed — useful for design preview).
  apiBaseUrl: 'https://api.ironcladdigital.agency',

  // Endpoints relative to apiBaseUrl.
  endpoints: {
    booking: '/v1/bookings',
    leadStatus: '/v1/bookings/:id',
  },

  // Public API key sent with requests (safe to expose in browser).
  // Server validates origin + rate-limits in addition to this.
  publicApiKey: '65c859b7b8f2aa055ade8c9d500b72db1a304c300259f36cc3073decb3e3e487',

  // ---------- Behavior ----------
  // When true, the API client logs request/response to console.
  debug: false,

  // Request timeout in milliseconds.
  requestTimeoutMs: 12000,

  // ---------- Integrations (informational — handled server-side) ----------
  // Listed here only so it's obvious to future devs what the
  // backend is expected to fan out to. The browser never talks
  // to these services directly.
  serverIntegrations: {
    sms: 'twilio',          // automated text notification (server/services/sms.js)
    email: 'twilio',        // automated email notification (server/services/email.js)
    crm: 'hubspot',         // CRM record + pipeline stage update (server/services/crm.js)
  },
});
