/**
 * Ironclad Digital — runtime configuration.
 *
 * Centralize anything environment-specific here so the rest of the
 * codebase doesn't have to change when endpoints, keys, or feature
 * flags evolve. When a real backend ships, only this file (and any
 * deployment-specific override) needs to be updated.
 *
 * In production this can be replaced/overridden at deploy time
 * (e.g. via a templated config.js generated by the host).
 */
window.IRONCLAD_CONFIG = Object.freeze({
  // ---------- API ----------
  // Base URL of the backend API.
  // Local dev: 'http://localhost:3001'
  // Production: 'https://api.ironcladdigital.agency'
  // Staging: 'https://staging-api.ironcladdigital.agency'
  // Leave empty to run in mock mode (no server needed — useful for design preview).
  apiBaseUrl: 'https://staging-api.ironcladdigital.agency',

  // Endpoints relative to apiBaseUrl.
  endpoints: {
    booking: '/v1/bookings',
    leadStatus: '/v1/bookings/:id',
  },

  // Public API key sent with requests (safe to expose in browser).
  // Server validates origin + rate-limits in addition to this.
  publicApiKey: '5b71fcec877165db829d72cadf1eac243096489c3905364d1c7695b87d000ffe',

  // ---------- Behavior ----------
  // When true, the API client logs request/response to console.
  debug: false,

  // Request timeout in milliseconds.
  requestTimeoutMs: 12000,

  // ---------- Integrations (informational — handled server-side) ----------
  // Listed here only so it's obvious to future devs what the
  // backend is expected to fan out to. The browser never talks
  // to these services directly.
  serverIntegrations: {
    sms: 'telnyx',          // automated text notification (api-core/services/sms.js)
    email: 'telnyx',        // automated email notification (api-core/services/email.js)
    crm: 'gohighlevel',     // CRM record + pipeline stage update (api-core/services/crm.js)
  },
});
